site_name: EDST8237 Aaron's Placement Portfolio
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - index.md
  - Preparations:
    - 'preparations/preparations.md'
    - 'preparations/planning.md'
    - 'preparations/paperwork.md'
    - 'preparations/timetable.md'
    - 'preparations/expectations.md'
  - Standards:
    - 'Standards/Standard1.md'
    - 'Standards/Standard2.md'
    - 'Standards/Standard3.md'
    - 'Standards/Standard4.md'
    - 'Standards/Standard5.md'
    - 'Standards/Standard6.md'
    - 'Standards/Standard7.md'
  - Lesson Plans:
    - LessonPlans/Overview.md
copyright: |
  &copy; 2024 <a href="https://github.com/aaron-beverley-mq" target="_blank" rel="noopener">Aaron Beverley</a>
